### ISSUE TITLE
Retour à la ligne dans le descriptif des news

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#50]
Si on met un texte très long sur une seule ligne, l'affichage des notes dépasse trop à droite.
Il faudrait un retour à la ligne automatique si la ligne dépasse, mais tout en conservant la mise en forme faite manuellement (les retours à la ligne forcé)

**Comment by mtthp** [comment]
Ok, c'est essentiellement un problème de CSS. La solution est décrite [ici](https://stackoverflow.com/a/638728) et il suffit d'ajouter les lignes suivantes à la balise _pre_ dans `client/src/components/Topic/TopicCard.vue:282` : 
```css
.topic.expanded .content pre {
  font-family: inherit;
  white-space: -moz-pre-wrap;
  white-space: -o-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}
```

Un peu hors-sujet : est-ce que c'est mieux de faire un hotfix à partir de la branche master actuelle ou d'ajouter ça à la PR ? ou même de te laisser faire le fix directement ?
